development:
  adapter: postgresql
  database: mun_ill_development
  pool: 5
  timeout: 5000

  test:
    adapter: postgresql
    database: mun_ill_development
    pool: 5
    timeout: 5000

  production:
    adapter: postgresql
    database: mun_ill_development
    pool: 5
    timeout: 5000
